name: t_store_e_com
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # utitlty packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.0
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  image_picker: ^1.1.0
  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6 

  # statemangment
  get: ^4.6.6
  get_storage: ^2.1.1

  #firebase
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.4
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.1
  cached_network_image: ^3.3.1
  
  
  
  
  
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/products/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    - assets/images/animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300  
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600  
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800  
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic 

    - family: Coolvetical
      fonts:
        - asset: assets/fonts/coolvetica-rg-it.otf
          weight: 400
          style: italic
        - asset: assets/fonts/coolvetica-rg.otf
          weight: 400  

