// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXQ3vGhO9f-S-IndFlQ2hSBJCiyjtXABM',
    appId: '1:746350150876:android:2d92202bf05b98f721e019',
    messagingSenderId: '746350150876',
    projectId: 't-shop-b4104',
    storageBucket: 't-shop-b4104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjmDkuvc11pLjx4KsWVHkAp5yDHbQkUc',
    appId: '1:746350150876:ios:c266ed1271625d6221e019',
    messagingSenderId: '746350150876',
    projectId: 't-shop-b4104',
    storageBucket: 't-shop-b4104.appspot.com',
    androidClientId: '746350150876-ij6vc67po22pafijmvvhsu84n2lr1jeh.apps.googleusercontent.com',
    iosClientId: '746350150876-qm9s90ds92d2d3dllqahgmt695eu7huo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStoreECom',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj9Xgo3xdOuF2LVOkiOoq5Bwdp5Vu7rvA',
    appId: '1:746350150876:web:59abdd051cc7558021e019',
    messagingSenderId: '746350150876',
    projectId: 't-shop-b4104',
    authDomain: 't-shop-b4104.firebaseapp.com',
    storageBucket: 't-shop-b4104.appspot.com',
    measurementId: 'G-3H5R2W43BJ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj9Xgo3xdOuF2LVOkiOoq5Bwdp5Vu7rvA',
    appId: '1:746350150876:web:4f41e42a5ecc5ada21e019',
    messagingSenderId: '746350150876',
    projectId: 't-shop-b4104',
    authDomain: 't-shop-b4104.firebaseapp.com',
    storageBucket: 't-shop-b4104.appspot.com',
    measurementId: 'G-81TWC8HQH7',
  );

}